language: node_js
node_js:
- 9
script:
- npm test
deploy:
  provider: heroku
  app: secure-peak-12589
  api_key:
    secure: qncsVNNNKuwAnA0ExGXWG8QdqWZ43R7p4yqZQmKxgBOMSSZIcCqyKZOI0wbiALDZWCrx10L0KYZAIPmgj26YRQJVJDnzKcq/Xj6n6nxawxvKK7RJUnaTJA2+PehO24874w3uOYZ3NgzZPab/fw6Q7o6TViUhcf+v2e6azP/Ji2NjUjaJtMyukWRCNCIdyNRDxON4wYoP2MLOBtR909eYXcEN6hxyfqnnuX6fiEsDpBitbRfOmdsZ0npGt61gmE9yx2rOvp/4IUfPKkJwBHBfP+CcTNjuvZBxKeNVnusEfem7L1W8h0G0t8rOrHEZjFTREwL7iLb3TirKKKLXxg3Pid5VjaDKyPzxNpYJkMoVLMblPgSBxeh0FeBFRypVuarPEOqh4OxpjQuxYixlRcXikIuLyFaxaLbwhXdo3wm9VIeikjbBBSUrzaUKB2UJjTtkSjoZgzcxhxPVnpV4mTzqGkyDl5XbLbj0a/LwHZ8tKZYIuCYjMptd3gNTf8ccS1MjAuzskrz6OaZrTTEaqlG+kzEl7+BPReIOQ+jtz0GSilc61APxhgBkVCjqkljaK4K83aoKXjj9aB8fswTjKmLUuRgTv8msWBSFU5CGiORTs3+yUNCGzct5/7m3OCLLDUKS2U70CJFHI40b1I8wVctIOPoncR/VOdU2LNdJ/UYNpzk=
